export type TableColumnType = {
	id: keyof TableRow
	label: string
	minWidth?: number
}

export const tableColumns: TableColumnType[] = [
	{
		id: 'name',
		label: 'ФИО',
		minWidth: 320,
	},
	{
		id: 'id',
		label: 'Внутр. номер',
		minWidth: 140,
	},
	{
		id: 'phone',
		label: 'Телефон',
		minWidth: 180,
	},
	{
		id: 'email',
		label: 'Почта',
		minWidth: 260,
	},
	{
		id: 'branch',
		label: 'Филиал',
		minWidth: 160,
	},
	{
		id: 'department',
		label: 'Отдел',
		minWidth: 160,
	},
	{
		id: 'post',
		label: 'Должность',
		minWidth: 200,
	},
	{
		id: 'director',
		label: 'Руководитель',
		minWidth: 180,
	},
	{
		id: 'experience',
		label: 'Стаж работы (лет)',
		minWidth: 180,
	},
	{
		id: 'age',
		label: 'Возраст',
		minWidth: 120,
	},
	{
		id: 'nationality',
		label: 'Гражданство',
		minWidth: 160,
	},
]

export type TableRow = {
	favorite?: boolean
	name: string
	id: string
	phone: string
	email: string
	branch: string
	department: string
	post: string
	director: string
	experience: number
	age: number
	nationality: string
}

export const tableRows: TableRow[] = [
	{
		name: 'Делия Эльги',
		id: 'B7309',
		phone: '+55 (240) 321-5142',
		email: 'delgyb@myspace.com',
		branch: 'Москва',
		department: 'Услуги',
		post: 'Генеральный менеджер',
		director: 'Делия Эльги',
		experience: 13,
		age: 47,
		nationality: 'Португалия',
	},
	{
		name: 'Дуранте Твелфтри',
		id: 'P7597',
		phone: '+678 (386) 903-4741',
		email: 'dedmonstonec@weather.com',
		branch: 'Москва',
		department: 'Маркетинг',
		post: 'Библиотекарь',
		director: 'Даррен Эдмонстоун',
		experience: 8,
		age: 47,
		nationality: 'Вануату',
	},
	{
		name: 'Афина Алесио',
		id: 'V1012',
		phone: '+1 (502) 331-3634',
		email: 'fcottad@tinyurl.com',
		branch: 'Москва',
		department: 'Продажи',
		post: 'Социальный работник',
		director: 'Фриман Котта',
		experience: 9,
		age: 49,
		nationality: 'Соединенные Штаты',
	},
	{
		name: 'Родина Осант',
		id: 'W9219',
		phone: '+62 (228) 987-6326',
		email: 'meadmeadese@dell.com',
		branch: 'Москва',
		department: 'Бухгалтерия',
		post: 'Ассистент по кадрам IV',
		director: 'Мэриголд Идмидс',
		experience: 17,
		age: 38,
		nationality: 'Индонезия',
	},
	{
		name: 'Консуэло Килти',
		id: 'D5768',
		phone: '+1 (619) 981-5733',
		email: 'rcoccif@ebay.co.uk',
		branch: 'Санкт-Петербург',
		department: 'Инженерия',
		post: 'Структурный инженер',
		director: 'Рета Кокки',
		experience: 16,
		age: 34,
		nationality: 'Соединенные Штаты',
	},
	{
		name: 'Фарли Керслейк',
		id: 'H2803',
		phone: '+62 (120) 164-2872',
		email: 'owaitingg@artisteer.com',
		branch: 'Москва',
		department: 'Кадры',
		post: 'Старший бухгалтер по затратам',
		director: 'Освальд Уэйтинг',
		experience: 17,
		age: 21,
		nationality: 'Индонезия',
	},
	{
		name: 'Геральт Бамлетт',
		id: 'W5870',
		phone: '+86 (752) 951-5098',
		email: 'gchidzoyh@oracle.com',
		branch: 'Москва',
		department: 'Продажи',
		post: 'Представитель по счетам III',
		director: 'Габи Чидзой',
		experience: 16,
		age: 42,
		nationality: 'Китай',
	},
	{
		name: 'Мендел Минго',
		id: 'A9279',
		phone: '+86 (994) 725-0625',
		email: 'gmassoni@tuttocitta.it',
		branch: 'Москва',
		department: 'Поддержка',
		post: 'Специалист по контролю качества',
		director: 'Горден Массон',
		experience: 16,
		age: 30,
		nationality: 'Китай',
	},
	{
		name: 'Паркер Рейли',
		id: 'U7873',
		phone: '+33 (728) 220-6019',
		email: 'mrossj@elegantthemes.com',
		branch: 'Москва',
		department: 'Кадры',
		post: 'Специалист по контролю качества',
		director: 'Мона Росс',
		experience: 15,
		age: 43,
		nationality: 'Франция',
	},
	{
		name: 'Марти Хоспитал',
		id: 'K0260',
		phone: '+62 (528) 233-6171',
		email: 'plegank@deliciousdays.com',
		branch: 'Москва',
		department: 'Развитие бизнеса',
		post: 'Геолог III',
		director: 'Петуния Леган',
		experience: 3,
		age: 49,
		nationality: 'Индонезия',
	},
	{
		name: "Дона О'Мэлли",
		id: 'K8464',
		phone: '+86 (281) 899-2307',
		email: 'scastagnel@foxnews.com',
		branch: 'Санкт-Петербург',
		department: 'Поддержка',
		post: 'Геолог II',
		director: 'Сальвидор Кастань',
		experience: 7,
		age: 45,
		nationality: 'Китай',
	},
	{
		name: 'Гильда Спиби',
		id: 'Z9195',
		phone: '+47 (339) 984-9094',
		email: 'mmeasenm@tripod.com',
		branch: 'Москва',
		department: 'Исследования и разработка',
		post: 'Аналитик по развитию бизнес-систем',
		director: 'Макси Мисен',
		experience: 19,
		age: 30,
		nationality: 'Норвегия',
	},
	{
		name: 'Bale Stallan',
		id: 'N2936',
		phone: '+62 (367) 217-8534',
		email: 'sbrookwood2a@1688.com',
		branch: 'asd',
		department: 'Support',
		post: 'Mechanical Systems Engineer',
		director: 'Sileas Brookwood',
		experience: 11,
		age: 28,
		nationality: 'Indonesia',
	},
	{
		name: 'Levey Valsler',
		id: 'X1531',
		phone: '+7 (236) 574-3728',
		email: 'mgregine2b@facebook.com',
		branch: 'www',
		department: 'Legal',
		post: 'Civil Engineer',
		director: 'Maria Gregine',
		experience: 16,
		age: 28,
		nationality: 'Russia',
	},
	{
		name: 'Kevyn Revens',
		id: 'K7697',
		phone: '+84 (960) 572-0172',
		email: 'kmaplestone2c@home.pl',
		branch: 'www',
		department: 'Support',
		post: 'Human Resources Manager',
		director: 'Kellen Maplestone',
		experience: 1,
		age: 36,
		nationality: 'Vietnam',
	},
	{
		name: 'Brook Alyoshin',
		id: 'M9096',
		phone: '+1 (515) 496-8635',
		email: 'drippin2d@sciencedaily.com',
		branch: 'asd',
		department: 'Product Management',
		post: 'Legal Assistant',
		director: 'Darrin Rippin',
		experience: 1,
		age: 43,
		nationality: 'United States',
	},
	{
		name: 'Chrissie Fonquernie',
		id: 'H7761',
		phone: '+351 (296) 262-9007',
		email: 'rwedlock2e@desdev.cn',
		branch: 'www',
		department: 'Human Resources',
		post: 'Media Manager III',
		director: 'Rhody Wedlock',
		experience: 10,
		age: 33,
		nationality: 'Portugal',
	},
	{
		name: 'Travers Spehr',
		id: 'K2785',
		phone: '+351 (957) 813-4256',
		email: 'ltallet2f@berkeley.edu',
		branch: 'asd',
		department: 'Support',
		post: 'Programmer III',
		director: 'Lindsy Tallet',
		experience: 14,
		age: 19,
		nationality: 'Portugal',
	},
	{
		name: 'Hyacinth Marshland',
		id: 'H4742',
		phone: '+63 (694) 245-9071',
		email: 'mselland2g@senate.gov',
		branch: 'asd',
		department: 'Training',
		post: 'Social Worker',
		director: 'Mireille Selland',
		experience: 10,
		age: 49,
		nationality: 'Philippines',
	},
	{
		name: 'Brittany Hamments',
		id: 'C1018',
		phone: '+53 (465) 256-8733',
		email: 'tdenkin2h@sina.com.cn',
		branch: 'asd',
		department: 'Legal',
		post: 'Food Chemist',
		director: 'Tybie Denkin',
		experience: 19,
		age: 39,
		nationality: 'Cuba',
	},
	{
		name: 'Fernanda Dymick',
		id: 'L4612',
		phone: '+998 (200) 538-3833',
		email: 'nmattisssen2i@npr.org',
		branch: 'asd',
		department: 'Human Resources',
		post: 'Software Consultant',
		director: 'Nicol Mattisssen',
		experience: 2,
		age: 46,
		nationality: 'Uzbekistan',
	},
	{
		name: 'Gram Adamek',
		id: 'Y4887',
		phone: '+62 (841) 389-2828',
		email: 'kbaynon2j@shinystat.com',
		branch: 'www',
		department: 'Human Resources',
		post: 'Structural Analysis Engineer',
		director: 'Kathi Baynon',
		experience: 20,
		age: 44,
		nationality: 'Indonesia',
	},
	{
		name: 'Killy McKnish',
		id: 'M7691',
		phone: '+63 (203) 720-0660',
		email: 'jslayford2k@telegraph.co.uk',
		branch: 'www',
		department: 'Business Development',
		post: 'Desktop Support Technician',
		director: 'Jesus Slayford',
		experience: 9,
		age: 18,
		nationality: 'Philippines',
	},
	{
		name: 'Ario Collett',
		id: 'F1096',
		phone: '+420 (404) 593-0274',
		email: 'gwithnall2l@goo.gl',
		branch: 'asd',
		department: 'Support',
		post: 'Safety Technician II',
		director: 'Gale Withnall',
		experience: 14,
		age: 38,
		nationality: 'Czech Republic',
	},
	{
		name: 'Manya Schrinel',
		id: 'E3804',
		phone: '+48 (612) 621-7336',
		email: 'jsapseed2m@howstuffworks.com',
		branch: 'www',
		department: 'Product Management',
		post: 'Compensation Analyst',
		director: 'Jocelyn Sapseed',
		experience: 17,
		age: 29,
		nationality: 'Poland',
	},
	{
		name: 'Rustie Calabry',
		id: 'P8581',
		phone: '+86 (295) 774-4369',
		email: 'fgascoine2n@theguardian.com',
		branch: 'www',
		department: 'Business Development',
		post: 'Software Consultant',
		director: 'Florinda Gascoine',
		experience: 19,
		age: 41,
		nationality: 'China',
	},
	{
		name: 'Vance Bannon',
		id: 'Q0016',
		phone: '+358 (421) 952-2404',
		email: 'mdikels2o@zimbio.com',
		branch: 'www',
		department: 'Business Development',
		post: 'Systems Administrator III',
		director: 'Mabel Dikels',
		experience: 19,
		age: 27,
		nationality: 'Finland',
	},
	{
		name: 'Con Snoxell',
		id: 'P0386',
		phone: '+55 (842) 769-7067',
		email: 'swillgoss2p@geocities.com',
		branch: 'www',
		department: 'Product Management',
		post: 'Senior Developer',
		director: 'Skipp Willgoss',
		experience: 9,
		age: 23,
		nationality: 'Brazil',
	},
	{
		name: 'Saunderson Ackers',
		id: 'Z3168',
		phone: '+380 (964) 790-2518',
		email: 'hkobierzycki2q@github.com',
		branch: 'www',
		department: 'Services',
		post: 'Sales Representative',
		director: 'Hastie Kobierzycki',
		experience: 14,
		age: 22,
		nationality: 'Ukraine',
	},
	{
		name: 'Constancy Hestrop',
		id: 'O5332',
		phone: '+220 (657) 750-0499',
		email: 'mcordobes2r@columbia.edu',
		branch: 'www',
		department: 'Accounting',
		post: 'Legal Assistant',
		director: 'Margaretta Cordobes',
		experience: 6,
		age: 47,
		nationality: 'Gambia',
	},
]
